### ISSUE TITLE
Not compatible with the latest version of Ulauncher

### ISSUE THREAD

**Issue by ghost** [nortmas/chrome-bookmarks#4] opened 2019-08-03 15:40 UTC
![image](https://user-images.githubusercontent.com/37113869/62413942-f818a580-b604-11e9-8c3e-c0a99be0b2af.png)

**Comment by pascalbe-dev** [comment] 2021-01-04 20:46
Can not reproduce. Works for me with the latest ulauncher version.

- ulauncher: 5.9.0
- extension api: 2.0.0

**Comment by nortmas** [comment] 2021-01-05 15:51
Me neither. Guess we can close it.

**Closed as completed by nortmas** 2021-01-05 15:51 UTC
